# Generated by Django 2.2 on 2020-07-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Stymulant'), ('D', 'Depresant'), ('H', 'Halucynogen')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
